"""HW2 — the environments. PROVIDED, complete. You do not edit this file.

HW0 asked you to *build* an environment. HW2 asks you to build the *learning
algorithm*, so both environments here are finished and handed to you. Read them
anyway — you cannot reason about a reward curve without knowing what the reward
is.

Two tasks, same pipeline you learned in HW0:

  Course-HW2-Cartpole-Balance         one pole.  Warm-up. Find your bugs here.
  Course-HW2-DoubleCartpole-Balance   two poles. The graded task.

Both start near-upright and are asked to *stay* upright. Swing-up is not part of
HW2 — see the "Why balance and not swing-up?" note in hw2/README.md.

THREE CHOICES HERE EXIST ONLY TO MAKE VANILLA POLICY GRADIENT WORK, and each one
is something PPO would let us drop:

  1. `is_finite_horizon=True`. The episode time limit is a real terminal, not an
     artificial cutoff. Nothing needs to estimate "the value of continuing", so
     REINFORCE — which has no value function in Part A — is well defined.
  2. `episode_length_s = 5.0`. With timestep=0.01 and decimation=5 the control
     step is 0.05 s, so an episode is exactly 100 control steps. The runner
     collects `num_steps_per_env = 100` steps, so ONE ITERATION IS EXACTLY ONE
     COMPLETE EPISODE PER ENV, all of them starting and ending together. That is
     what makes a Monte-Carlo return exact instead of an approximation.
  3. `num_envs = 1024` by default. REINFORCE's gradient estimate is unbiased but
     very high variance; the only cheap fix is to average over a lot of episodes.

Note `scale_rewards_by_dt` is mjlab's default (True), so every per-step reward
below is multiplied by the 0.05 s control step before you see it. A perfect
100-step episode scores about 5.0, not 100. Do not go looking for the missing
factor of 20.
"""

from __future__ import annotations

import math
from pathlib import Path
from typing import TYPE_CHECKING

import mujoco
import torch

from mjlab.actuator.xml_actuator import XmlActuatorCfg
from mjlab.entity import Entity, EntityArticulationInfoCfg, EntityCfg
from mjlab.envs import ManagerBasedRlEnvCfg
from mjlab.envs.mdp import (
  joint_pos_rel,
  joint_vel_rel,
  reset_joints_by_offset,
  time_out,
)
from mjlab.envs.mdp.actions import JointEffortActionCfg
from mjlab.managers.action_manager import ActionTermCfg
from mjlab.managers.event_manager import EventTermCfg
from mjlab.managers.observation_manager import (
  ObservationGroupCfg,
  ObservationTermCfg,
)
from mjlab.managers.reward_manager import RewardTermCfg
from mjlab.managers.scene_entity_config import SceneEntityCfg
from mjlab.managers.termination_manager import TerminationTermCfg
from mjlab.scene import SceneCfg
from mjlab.sim import MujocoCfg, SimulationCfg
from mjlab.terrains import TerrainEntityCfg
from mjlab.viewer import ViewerConfig

if TYPE_CHECKING:
  from mjlab.envs import ManagerBasedRlEnv

# ---------------------------------------------------------------------------
# 1. Entities.
#
# HW2 keeps its own copies of the two MJCF files so this assignment stands on
# its own: nothing here imports from course_tasks.hw0, so an unfinished HW0
# cannot break HW2.
# ---------------------------------------------------------------------------

_CARTPOLE_XML: Path = Path(__file__).parent / "cartpole.xml"
_CARTPOLE_DOUBLE_XML: Path = Path(__file__).parent / "cartpole_double.xml"

# Single-pole selectors.
_CART_CFG = SceneEntityCfg("cartpole", joint_names=("slider",))
_HINGE_CFG = SceneEntityCfg("cartpole", joint_names=("hinge_1",))
# Double-pole selectors. _HINGES_CFG selects BOTH hinges at once, so terms that
# take it get a [num_envs, 2] slice instead of [num_envs, 1].
_HINGES_CFG = SceneEntityCfg("cartpole", joint_names=("hinge_1", "hinge_2"))

_ARTICULATION = EntityArticulationInfoCfg(
  actuators=(XmlActuatorCfg(target_names_expr=("slider",)),),
)


def _get_single_spec() -> mujoco.MjSpec:
  return mujoco.MjSpec.from_file(str(_CARTPOLE_XML))


def _get_double_spec() -> mujoco.MjSpec:
  return mujoco.MjSpec.from_file(str(_CARTPOLE_DOUBLE_XML))


# Both variants start upright. hinge_2 is measured RELATIVE to pole_1, so
# hinge_1 = hinge_2 = 0 is the fully extended, straight-up configuration.
_SINGLE_INIT = EntityCfg.InitialStateCfg(
  pos=(0.0, 0.0, 0.0),
  joint_pos={"slider": 0.0, "hinge_1": 0.0},
  joint_vel={".*": 0.0},
)
_DOUBLE_INIT = EntityCfg.InitialStateCfg(
  pos=(0.0, 0.0, 0.0),
  joint_pos={"slider": 0.0, "hinge_1": 0.0, "hinge_2": 0.0},
  joint_vel={".*": 0.0},
)


def _get_single_cfg() -> EntityCfg:
  return EntityCfg(
    spec_fn=_get_single_spec,
    articulation=_ARTICULATION,
    init_state=_SINGLE_INIT,
  )


def _get_double_cfg() -> EntityCfg:
  return EntityCfg(
    spec_fn=_get_double_spec,
    articulation=_ARTICULATION,
    init_state=_DOUBLE_INIT,
  )


# ---------------------------------------------------------------------------
# 2. Observations.
#
# Same trick as HW0: feed (cos, sin) rather than the raw angle so the policy
# never sees the 2*pi wrap-around as a discontinuity. Works for one hinge or
# several — the output is [num_envs, 2 * n_joints].
# ---------------------------------------------------------------------------


def pole_angle_cos_sin(
  env: ManagerBasedRlEnv,
  asset_cfg: SceneEntityCfg = _HINGE_CFG,
) -> torch.Tensor:
  """Cosine and sine of each selected hinge angle. Shape: [num_envs, 2 * n]."""
  asset: Entity = env.scene[asset_cfg.name]
  angle = asset.data.joint_pos[:, asset_cfg.joint_ids]
  return torch.cat([torch.cos(angle), torch.sin(angle)], dim=-1)


# ---------------------------------------------------------------------------
# 3. Rewards.
#
# dm_control's smooth cartpole reward: a PRODUCT of factors in [0, 1], which
# behaves like a soft AND. Reward is high only when the pole is up AND the cart
# is centered AND the control is small AND nothing is moving fast.
#
# Everything is a batched torch op over all num_envs at once. Never write a
# Python loop over environments.
# ---------------------------------------------------------------------------

_GAUSSIAN_SCALE = math.sqrt(-2 * math.log(0.1))  # value_at_margin = 0.1
_QUADRATIC_SCALE = math.sqrt(1 - 0.1)


def _gaussian_tolerance(x: torch.Tensor, margin: float) -> torch.Tensor:
  """1 at x=0, decaying to 0.1 at |x| = margin."""
  if margin == 0:
    return (x == 0).float()
  scaled = x / margin * _GAUSSIAN_SCALE
  return torch.exp(-0.5 * scaled**2)


def _quadratic_tolerance(x: torch.Tensor, margin: float) -> torch.Tensor:
  """1 at x=0, hitting exactly 0 for |x| >= margin."""
  if margin == 0:
    return (x == 0).float()
  scaled = x / margin * _QUADRATIC_SCALE
  return torch.clamp(1 - scaled**2, min=0.0)


def cartpole_smooth_reward(
  env: ManagerBasedRlEnv,
  cart_cfg: SceneEntityCfg = _CART_CFG,
  hinge_cfg: SceneEntityCfg = _HINGE_CFG,
) -> torch.Tensor:
  """upright * centered * small_control * small_velocity. Shape: [num_envs]."""
  asset: Entity = env.scene[cart_cfg.name]

  hinge_angle = asset.data.joint_pos[:, hinge_cfg.joint_ids].squeeze(-1)
  upright = (torch.cos(hinge_angle) + 1) / 2

  cart_pos = asset.data.joint_pos[:, cart_cfg.joint_ids].squeeze(-1)
  centered = (1 + _gaussian_tolerance(cart_pos, margin=2.0)) / 2

  control = env.action_manager.action.squeeze(-1)
  small_control = (4 + _quadratic_tolerance(control, margin=1.0)) / 5

  hinge_vel = asset.data.joint_vel[:, hinge_cfg.joint_ids].squeeze(-1)
  small_velocity = (1 + _gaussian_tolerance(hinge_vel, margin=5.0)) / 2

  return upright * centered * small_control * small_velocity


def cartpole_double_smooth_reward(
  env: ManagerBasedRlEnv,
  cart_cfg: SceneEntityCfg = _CART_CFG,
  hinges_cfg: SceneEntityCfg = _HINGES_CFG,
) -> torch.Tensor:
  """Two-link version of the above. Shape: [num_envs].

  `hinge_2` is measured relative to `pole_1`, so "both links vertical" is the
  single condition hinge_1 = hinge_2 = 0 — no angle summing required. Taking the
  product over the two `upright` factors keeps the soft-AND behaviour: bending at
  either joint costs reward.
  """
  asset: Entity = env.scene[cart_cfg.name]

  # [num_envs, 2] -> one upright factor per link, then multiply them together.
  hinge_angles = asset.data.joint_pos[:, hinges_cfg.joint_ids]
  upright = ((torch.cos(hinge_angles) + 1) / 2).prod(dim=-1)

  cart_pos = asset.data.joint_pos[:, cart_cfg.joint_ids].squeeze(-1)
  centered = (1 + _gaussian_tolerance(cart_pos, margin=2.0)) / 2

  control = env.action_manager.action.squeeze(-1)
  small_control = (4 + _quadratic_tolerance(control, margin=1.0)) / 5

  # Slowest link decides: take the largest absolute hinge velocity.
  hinge_vel = asset.data.joint_vel[:, hinges_cfg.joint_ids].abs().amax(dim=-1)
  small_velocity = (1 + _gaussian_tolerance(hinge_vel, margin=5.0)) / 2

  return upright * centered * small_control * small_velocity


# ---------------------------------------------------------------------------
# 4. Terminations.
# ---------------------------------------------------------------------------


def joint_velocity_limit_exceeded(
  env: ManagerBasedRlEnv,
  asset_cfg: SceneEntityCfg,
  limit: float,
) -> torch.Tensor:
  """Terminate if any of the selected joints' velocity exceeds `limit`.

  Safety guard against the double pendulum's chaotic dynamics driving joint
  velocity into the regime where mujoco-warp's fixed-timestep integrator
  diverges. `limit` is set far above anything a normal balance needs, so this
  only fires on genuinely runaway states.
  """
  asset: Entity = env.scene[asset_cfg.name]
  vel = asset.data.joint_vel[:, asset_cfg.joint_ids]
  return (vel.abs() > limit).any(dim=-1)


# ---------------------------------------------------------------------------
# 5. Assemble.
# ---------------------------------------------------------------------------

# One episode = 5.0 s / (0.01 s * 5) = 100 control steps. The runner's
# num_steps_per_env must match this — see runner.py.
EPISODE_LENGTH_S = 5.0
SIM_TIMESTEP = 0.01
DECIMATION = 5
STEPS_PER_EPISODE = int(round(EPISODE_LENGTH_S / (SIM_TIMESTEP * DECIMATION)))


def _make_env_cfg(double: bool) -> ManagerBasedRlEnvCfg:
  hinge_cfg = _HINGES_CFG if double else _HINGE_CFG
  reward_fn = cartpole_double_smooth_reward if double else cartpole_smooth_reward
  reward_params = (
    {"cart_cfg": _CART_CFG, "hinges_cfg": _HINGES_CFG}
    if double
    else {"cart_cfg": _CART_CFG, "hinge_cfg": _HINGE_CFG}
  )

  actor_terms = {
    "cart_pos": ObservationTermCfg(func=joint_pos_rel, params={"asset_cfg": _CART_CFG}),
    "pole_angle": ObservationTermCfg(
      func=pole_angle_cos_sin, params={"asset_cfg": hinge_cfg}
    ),
    "cart_vel": ObservationTermCfg(func=joint_vel_rel, params={"asset_cfg": _CART_CFG}),
    "pole_vel": ObservationTermCfg(func=joint_vel_rel, params={"asset_cfg": hinge_cfg}),
  }
  observations = {
    "actor": ObservationGroupCfg(actor_terms, enable_corruption=True),
    "critic": ObservationGroupCfg({**actor_terms}),
  }

  actions: dict[str, ActionTermCfg] = {
    "effort": JointEffortActionCfg(
      entity_name="cartpole",
      actuator_names=("slider",),
      scale=1.0,
    ),
  }

  # Start near-upright with a small random perturbation. Without this the policy
  # would only ever see one trajectory and could memorize it.
  events = {
    "reset_slider": EventTermCfg(
      func=reset_joints_by_offset,
      mode="reset",
      params={
        "position_range": (-0.1, 0.1),
        "velocity_range": (-0.01, 0.01),
        "asset_cfg": _CART_CFG,
      },
    ),
    "reset_hinges": EventTermCfg(
      func=reset_joints_by_offset,
      mode="reset",
      params={
        "position_range": (-0.034, 0.034),
        "velocity_range": (-0.01, 0.01),
        "asset_cfg": hinge_cfg,
      },
    ),
  }

  rewards = {
    "smooth_reward": RewardTermCfg(
      func=reward_fn,
      weight=1.0,
      params=reward_params,
    ),
  }

  # With is_finite_horizon=True below, hitting the time limit is a genuine
  # terminal: there is no "value of continuing" past the horizon to bootstrap.
  terminations = {
    "time_out": TerminationTermCfg(func=time_out, time_out=True),
  }
  if double:
    terminations["velocity_limit"] = TerminationTermCfg(
      func=joint_velocity_limit_exceeded,
      params={"asset_cfg": _HINGES_CFG, "limit": 50.0},
    )

  return ManagerBasedRlEnvCfg(
    scene=SceneCfg(
      terrain=TerrainEntityCfg(terrain_type="plane"),
      entities={"cartpole": _get_double_cfg() if double else _get_single_cfg()},
      num_envs=1024,
      env_spacing=4.0,
    ),
    observations=observations,
    actions=actions,
    events=events,
    rewards=rewards,
    terminations=terminations,
    viewer=ViewerConfig(
      origin_type=ViewerConfig.OriginType.ASSET_BODY,
      entity_name="cartpole",
      body_name="cart",
      distance=5.0 if double else 4.0,
      elevation=-15.0,
      azimuth=0.0,
    ),
    sim=SimulationCfg(
      mujoco=MujocoCfg(timestep=SIM_TIMESTEP, disableflags=("contact",)),
    ),
    decimation=DECIMATION,
    episode_length_s=EPISODE_LENGTH_S,
    # See the module docstring: this is what makes a Monte-Carlo return exact.
    is_finite_horizon=True,
  )


def cartpole_balance_env_cfg(play: bool = False) -> ManagerBasedRlEnvCfg:
  cfg = _make_env_cfg(double=False)
  if play:
    cfg.episode_length_s = 1e10
    cfg.observations["actor"].enable_corruption = False
  return cfg


def cartpole_double_balance_env_cfg(play: bool = False) -> ManagerBasedRlEnvCfg:
  cfg = _make_env_cfg(double=True)
  if play:
    cfg.episode_length_s = 1e10
    cfg.observations["actor"].enable_corruption = False
  return cfg
