"""HW2 — the policy and value networks. PROVIDED. You do not edit this file.

Two plain `nn.Module`s, written out in full rather than pulled from rsl_rl, so
that every quantity in the policy-gradient formula has a line of code you can
point at.

  GaussianActor   s -> pi(a|s) = Normal(mean=MLP(s), std=exp(log_std))
  Critic          s -> V(s), a single scalar

The actor's standard deviation is a free parameter, NOT a function of the state.
That is the standard choice for continuous control and it matters for you in two
ways:

  * It is the policy's only source of exploration. Watch `Policy/mean_std` in
    W&B: if it collapses toward zero in the first few iterations your policy has
    stopped exploring and the run is dead, 
    whatever the reward curve says.
  * The entropy bonus in `update()` is what pushes back against that collapse.

`distribution()` returns a `torch.distributions.Normal` and nothing is cached on
`self`. Call it as many times as you like, in any order — unlike rsl_rl's
`MLPModel`, where `forward(stochastic_output=True)` mutates a hidden
distribution that `get_output_log_prob()` then reads back, and call order is
load-bearing.
"""

from __future__ import annotations

import math

import torch
import torch.nn as nn
from torch.distributions import Normal

_ACTIVATIONS: dict[str, type[nn.Module]] = {
  "elu": nn.ELU,
  "relu": nn.ReLU,
  "tanh": nn.Tanh,
}


def _make_mlp(
  input_dim: int,
  output_dim: int,
  hidden_dims: tuple[int, ...],
  activation: str,
) -> nn.Sequential:
  act = _ACTIVATIONS[activation]
  layers: list[nn.Module] = []
  prev = input_dim
  for dim in hidden_dims:
    layers.append(nn.Linear(prev, dim))
    layers.append(act())
    prev = dim
  layers.append(nn.Linear(prev, output_dim))
  return nn.Sequential(*layers)


class GaussianActor(nn.Module):
  """Diagonal-Gaussian policy with a state-independent, learnable std."""

  def __init__(
    self,
    obs_dim: int,
    action_dim: int,
    hidden_dims: tuple[int, ...] = (64, 64),
    activation: str = "elu",
    init_std: float = 1.0,
  ) -> None:
    super().__init__()
    self.mlp = _make_mlp(obs_dim, action_dim, hidden_dims, activation)
    self.log_std = nn.Parameter(torch.full((action_dim,), math.log(init_std)))

  @property
  def std(self) -> torch.Tensor:
    # Clamped so a diverging update cannot produce a degenerate distribution.
    return self.log_std.clamp(-5.0, 2.0).exp()

  def distribution(self, obs: torch.Tensor) -> Normal:
    """pi(.|s) for a batch of observations. obs: [..., obs_dim]."""
    mean = self.mlp(obs)
    return Normal(mean, self.std.expand_as(mean))

  def forward(self, obs: torch.Tensor) -> torch.Tensor:
    """Deterministic action (the distribution mean). Used at play time."""
    return self.mlp(obs)

  def act(self, obs: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
    """Sample an action and return it with its log-probability.

    Returns:
      actions:   [batch, action_dim]
      log_probs: [batch]   (summed over the action dimension)
    """
    dist = self.distribution(obs)
    actions = dist.sample()
    return actions, dist.log_prob(actions).sum(dim=-1)

  def evaluate_actions(
    self, obs: torch.Tensor, actions: torch.Tensor
  ) -> tuple[torch.Tensor, torch.Tensor]:
    """Re-score already-taken actions under the CURRENT policy.

    This is the function that carries gradients into the policy loss, and it is
    also exactly what PPO needs to form its probability ratio.

    Returns:
      log_probs: [batch]
      entropy:   [batch]
    """
    dist = self.distribution(obs)
    return dist.log_prob(actions).sum(dim=-1), dist.entropy().sum(dim=-1)


class Critic(nn.Module):
  """State-value function V(s). Only used when baseline="value"."""

  def __init__(
    self,
    obs_dim: int,
    hidden_dims: tuple[int, ...] = (64, 64),
    activation: str = "elu",
  ) -> None:
    super().__init__()
    self.mlp = _make_mlp(obs_dim, 1, hidden_dims, activation)

  def forward(self, obs: torch.Tensor) -> torch.Tensor:
    """V(s). obs: [..., obs_dim] -> [...]  (the trailing 1 is squeezed off)."""
    return self.mlp(obs).squeeze(-1)
