"""HW2 — the training loop and its configs. PROVIDED. You do not edit this file.

`ReinforceRunner` is what mjlab's `uv run train` and `uv run play` drive for
every HW2 task. It runs whichever algorithm the task's config names:

  algorithm.class_name == "Reinforce"   -> reinforce.Reinforce  (provided)
  algorithm.class_name == "PPO"         -> ppo.PPO              (yours)

It is plugged into mjlab through `register_mjlab_task(..., runner_cls=...)` in
`__init__.py`. docs/02_custom_algorithms.md explains that hook, the exact calls
train/play make on this class, and the logistics of adding an algorithm.
"""

from __future__ import annotations

import os
import statistics
import time
from dataclasses import dataclass, field
from typing import Any, Literal

import torch
from mjlab.rl import RslRlBaseRunnerCfg
from rsl_rl.utils.logger import Logger

from course_tasks.hw2.env_cfg import STEPS_PER_EPISODE
from course_tasks.hw2.modules import Critic, GaussianActor
from course_tasks.hw2.ppo import PPO
from course_tasks.hw2.reinforce import Reinforce
from course_tasks.hw2.storage import RolloutStorage

# ---------------------------------------------------------------------------
# Configs.
#
# Every field below becomes a CLI flag, because tyro specializes on the concrete
# type of the registered default config. So from the command line:
#
#   --agent.algorithm.baseline none
#   --agent.algorithm.clip-param 0.1          (PPO tasks only)
#   --agent.num-steps-per-env 24              (PPO tasks only; REINFORCE rejects it)
#   --agent.max-iterations 50
# ---------------------------------------------------------------------------


@dataclass
class ReinforceAlgorithmCfg:
  """Hyperparameters shared by REINFORCE and PPO."""

  gamma: float = 0.99
  """Discount factor."""
  learning_rate: float = 1.0e-3
  """Adam learning rate. Fixed — there is no learning-rate schedule here."""
  entropy_coef: float = 0.005
  """Weight on the entropy bonus. Fights premature collapse of the policy std."""
  value_loss_coef: float = 0.5
  """Weight on the critic's MSE loss. Ignored when baseline="none"."""
  max_grad_norm: float = 1.0
  """Gradient-norm clip. Policy gradients are spiky; this is not optional."""
  baseline: Literal["none", "value"] = "value"
  """"none" = plain REINFORCE (A = G). "value" = subtract a learned V(s)."""
  normalize_advantage: bool = True
  """Standardize advantages to zero mean / unit std before the update."""
  class_name: str = "Reinforce"
  """Which algorithm the runner builds: "Reinforce" or "PPO"."""


@dataclass
class PpoAlgorithmCfg(ReinforceAlgorithmCfg):
  """Adds PPO's hyperparameters. Defaults match HW0's rsl_rl PPO config."""

  clip_param: float = 0.2
  """Clipping range epsilon for the probability ratio."""
  lam: float = 0.95
  """GAE lambda."""
  num_learning_epochs: int = 5
  """Passes over each rollout per iteration."""
  num_mini_batches: int = 4
  """Minibatches per pass."""
  class_name: str = "PPO"


@dataclass
class ReinforceRunnerCfg(RslRlBaseRunnerCfg):
  """Runner config for the REINFORCE tasks."""

  class_name: str = "ReinforceRunner"
  hidden_dims: tuple[int, ...] = (64, 64)
  """Hidden layer sizes, shared by the actor and the critic."""
  activation: str = "elu"
  init_std: float = 1.0
  """Initial standard deviation of the Gaussian policy."""
  algorithm: ReinforceAlgorithmCfg = field(default_factory=ReinforceAlgorithmCfg)

  # rsl_rl deprecates the plain string cfg["logger"] = "wandb" in favour of this
  # dict form. mjlab's base cfg types `logger` as Literal["wandb","tensorboard"]
  # and so cannot express it; overriding the field here takes the non-deprecated
  # path. REINFORCE and PPO share one project so their runs overlay directly.
  logger: dict[str, Any] = field(  # pyright: ignore[reportIncompatibleVariableOverride]
    default_factory=lambda: {
      "class_name": "WandbLogWriter",
      "project_name": "cs498-hw2",
    }
  )


@dataclass
class PpoRunnerCfg(ReinforceRunnerCfg):
  """Runner config for the PPO tasks."""

  algorithm: PpoAlgorithmCfg = field(default_factory=PpoAlgorithmCfg)  # pyright: ignore[reportIncompatibleVariableOverride]


# ---------------------------------------------------------------------------
# Runner.
# ---------------------------------------------------------------------------

_ALGORITHMS: dict[str, type] = {"Reinforce": Reinforce, "PPO": PPO}
_SHARED_KEYS = (
  "gamma",
  "learning_rate",
  "entropy_coef",
  "value_loss_coef",
  "max_grad_norm",
  "baseline",
  "normalize_advantage",
)
_PPO_KEYS = ("clip_param", "lam", "num_learning_epochs", "num_mini_batches")


class ReinforceRunner:
  """Drives collection and learning for `Reinforce` or `PPO`.

  Implements the duck-typed contract mjlab's train/play scripts expect:
  `__init__(env, cfg, log_dir, device)`, `learn`, `save`, `load`,
  `get_inference_policy`, `add_git_repo_to_log`.
  """

  def __init__(
    self,
    env,
    train_cfg: dict,
    log_dir: str | None = None,
    device: str = "cpu",
  ) -> None:
    self.env = env
    self.cfg = train_cfg
    self.device = device
    self.alg_cfg = train_cfg["algorithm"]

    class_name = self.alg_cfg["class_name"]
    if class_name not in _ALGORITHMS:
      raise ValueError(
        f"Unknown algorithm.class_name {class_name!r}; expected one of {sorted(_ALGORITHMS)}."
      )

    num_steps = train_cfg["num_steps_per_env"]
    if class_name == "Reinforce" and num_steps != STEPS_PER_EPISODE:
      # REINFORCE's Monte-Carlo return is only a return if every rollout is a
      # complete episode. Fail loudly rather than train on something else.
      raise ValueError(
        f"REINFORCE requires num_steps_per_env == {STEPS_PER_EPISODE} (one full "
        f"episode per iteration), got {num_steps}. See env_cfg.py."
      )
    if num_steps < 1:
      raise ValueError(f"num_steps_per_env must be >= 1, got {num_steps}.")

    obs = self._policy_obs(self.env.get_observations())
    obs_dim = obs.shape[-1]

    hidden_dims = tuple(train_cfg["hidden_dims"])
    actor = GaussianActor(
      obs_dim=obs_dim,
      action_dim=self.env.num_actions,
      hidden_dims=hidden_dims,
      activation=train_cfg["activation"],
      init_std=train_cfg["init_std"],
    ).to(device)
    critic = Critic(
      obs_dim=obs_dim,
      hidden_dims=hidden_dims,
      activation=train_cfg["activation"],
    ).to(device)

    storage = RolloutStorage(
      num_transitions_per_env=num_steps,
      num_envs=self.env.num_envs,
      obs_dim=obs_dim,
      action_dim=self.env.num_actions,
      device=device,
    )

    kwargs = {k: self.alg_cfg[k] for k in _SHARED_KEYS}
    if class_name == "PPO":
      kwargs.update({k: self.alg_cfg[k] for k in _PPO_KEYS})
    self.alg = _ALGORITHMS[class_name](
      actor=actor, critic=critic, storage=storage, device=device, **kwargs
    )

    self.logger = Logger(
      log_dir=log_dir,
      cfg=self.cfg,
      env_cfg=self.env.cfg,
      num_envs=self.env.num_envs,
      is_distributed=False,
      gpu_world_size=1,
      gpu_global_rank=0,
      device=self.device,
    )
    self.current_learning_iteration = 0

  @staticmethod
  def _policy_obs(obs) -> torch.Tensor:
    """Pull the plain [num_envs, obs_dim] tensor out of mjlab's TensorDict.

    mjlab hands back a TensorDict keyed by observation group ("actor",
    "critic"). HW2's two groups hold the identical terms — the only difference
    is that "actor" has noise corruption enabled during training — so the
    algorithm works with a single tensor and both the policy and the value
    function see the same observations.
    """
    return obs["actor"]

  # -- Training. ------------------------------------------------------------

  def learn(
    self, num_learning_iterations: int, init_at_random_ep_len: bool = False
  ) -> None:
    """Collect `num_steps_per_env` steps per env, learn, repeat.

    `init_at_random_ep_len` is accepted for interface compatibility and
    deliberately IGNORED. mjlab's train.py always passes True, which staggers
    episode boundaries across environments. HW2 keeps every environment's
    episodes aligned, so that for REINFORCE a column of the buffer is exactly
    one complete trajectory, and so REINFORCE and PPO see the same data.
    """
    del init_at_random_ep_len

    obs = self._policy_obs(self.env.get_observations().to(self.device))
    self.alg.train_mode()
    self.logger.init_logging_writer()

    start_it = self.current_learning_iteration
    total_it = start_it + num_learning_iterations

    for it in range(start_it, total_it):
      start = time.time()

      # Collection. inference_mode makes every tensor produced in here
      # non-differentiable, which is why update() re-scores the actions rather
      # than reusing the log-probs stored below.
      with torch.inference_mode():
        self.alg.storage.clear()
        for _ in range(self.cfg["num_steps_per_env"]):
          actions = self.alg.act(obs)
          obs, rewards, dones, extras = self.env.step(actions.to(self.env.device))
          obs = self._policy_obs(obs.to(self.device))
          rewards = rewards.to(self.device)
          dones = dones.to(self.device)
          # The env auto-resets done environments, so on a done step `obs` is
          # the first observation of the NEXT episode. Anything that bootstraps
          # from the last observation must therefore mask it with (1 - done).
          self.alg.process_env_step(rewards, dones)
          self.logger.process_env_step(rewards, dones, extras)

        collect_time = time.time() - start

      # Deliberately OUTSIDE the inference_mode block above. These write fresh
      # tensors into the storage buffers, and a tensor created inside
      # inference_mode can never take part in a backward pass — update() would
      # die with "Inference tensors cannot be saved for backward".
      start = time.time()
      self.alg.compute_returns(obs)
      self.alg.compute_advantages()
      loss_dict = self.alg.update()

      learn_time = time.time() - start
      self.current_learning_iteration = it

      self.logger.log(
        it=it,
        start_it=start_it,
        total_it=total_it,
        collect_time=collect_time,
        learn_time=learn_time,
        loss_dict=loss_dict,
        learning_rate=self.alg.learning_rate,
        action_std=self.alg.actor.std.detach(),
        rnd_weight=None,
      )

      if self.logger.writer is not None:
        # rsl_rl logs every W&B scalar against the iteration number and only
        # prints total steps to the console. Runs with different rollout
        # lengths collect different amounts of data per iteration, so compare
        # them against this instead: set the W&B x-axis to it.
        self.logger.writer.add_scalar(
          "Train/total_env_steps", self.logger.tot_timesteps, it
        )
        if it % self.cfg["save_interval"] == 0:
          self.save(os.path.join(str(self.logger.log_dir), f"model_{it}.pt"))

    if self.logger.writer is not None:
      self.save(
        os.path.join(
          str(self.logger.log_dir), f"model_{self.current_learning_iteration}.pt"
        )
      )
      self.logger.stop_logging_writer()

  # -- Checkpointing. -------------------------------------------------------

  def save(self, path: str, infos: dict | None = None) -> None:
    saved_dict = self.alg.state_dict()
    saved_dict["iter"] = self.current_learning_iteration
    saved_dict["infos"] = {
      **(infos or {}),
      "env_state": {"common_step_counter": self.env.unwrapped.common_step_counter},
    }
    torch.save(saved_dict, path)
    if self.cfg.get("upload_model", True):
      self.logger.save_model(path, self.current_learning_iteration)

  def load(
    self,
    path: str,
    load_cfg: dict | None = None,
    strict: bool = True,
    map_location: str | None = None,
  ) -> dict:
    # `play` passes load_cfg={"actor": True}; we always restore everything the
    # checkpoint holds, which is a superset.
    del load_cfg
    loaded = torch.load(path, map_location=map_location, weights_only=False)
    self.alg.load_state_dict(loaded, strict=strict)
    self.current_learning_iteration = loaded.get("iter", 0)
    infos = loaded.get("infos") or {}
    if "env_state" in infos:
      self.env.unwrapped.common_step_counter = infos["env_state"][
        "common_step_counter"
      ]
    return infos

  # -- Inference. -----------------------------------------------------------

  def get_inference_policy(self, device: str | None = None):
    """Return a callable obs_dict -> action for `uv run play`.

    Plays the distribution MEAN, not a sample: at evaluation time you want the
    policy's best guess, not its exploration noise.
    """
    self.alg.eval_mode()
    actor = self.alg.actor
    if device is not None:
      actor = actor.to(device)

    def policy(obs):
      with torch.inference_mode():
        return actor(self._policy_obs(obs))

    return policy

  def add_git_repo_to_log(self, repo_file_path: str) -> None:
    self.logger.git_status_repos.append(repo_file_path)

  # -- Misc. ----------------------------------------------------------------

  @property
  def mean_reward(self) -> float:
    return statistics.mean(self.logger.rewbuffer) if self.logger.rewbuffer else 0.0
