"""HW2 — the rollout buffer. PROVIDED. You do not edit this file.

A fixed-size buffer for one iteration of on-policy data. Every tensor is
`[T, N, ...]` where T = `num_steps_per_env` and N = `num_envs`, so `rewards[t]`
is "the reward all N environments got at step t".

In HW2, T is exactly one episode (see env_cfg.py), so a column of this buffer is
one complete trajectory. That is the whole reason `compute_returns` can be a
plain backwards scan with no bootstrapping.

Unlike rsl_rl's `RolloutStorage`, there is no trailing singleton dimension on the
scalar fields — `rewards` is `[T, N]`, not `[T, N, 1]`. That is why you will not
find a single `torch.squeeze` in reinforce.py.

`minibatch_generator` is here but REINFORCE never calls it: one iteration of
vanilla policy gradient is a single full-batch gradient step. It is provided
because PPO does multiple epochs over shuffled minibatches of exactly this
buffer, so the extension needs no new file.
"""

from __future__ import annotations

from typing import Generator

import torch


class RolloutStorage:
  """Flat `[T, N, ...]` storage for one on-policy iteration."""

  def __init__(
    self,
    num_transitions_per_env: int,
    num_envs: int,
    obs_dim: int,
    action_dim: int,
    device: str | torch.device,
  ) -> None:
    self.num_transitions_per_env = num_transitions_per_env
    self.num_envs = num_envs
    self.device = device

    t, n = num_transitions_per_env, num_envs
    self.observations = torch.zeros(t, n, obs_dim, device=device)
    self.actions = torch.zeros(t, n, action_dim, device=device)
    # The log-prob of each action under the policy that ACTUALLY TOOK IT.
    # Detached at collection time; update() recomputes a fresh, differentiable
    # copy. PPO compares the two to form its ratio.
    self.old_log_probs = torch.zeros(t, n, device=device)
    self.rewards = torch.zeros(t, n, device=device)
    self.dones = torch.zeros(t, n, device=device)
    self.values = torch.zeros(t, n, device=device)

    # Filled in by the algorithm, not by the collection loop.
    self.returns = torch.zeros(t, n, device=device)
    self.advantages = torch.zeros(t, n, device=device)

    self.step = 0

  def add_transition(
    self,
    observations: torch.Tensor,
    actions: torch.Tensor,
    log_probs: torch.Tensor,
    rewards: torch.Tensor,
    dones: torch.Tensor,
    values: torch.Tensor,
  ) -> None:
    if self.step >= self.num_transitions_per_env:
      raise RuntimeError(
        f"RolloutStorage is full ({self.num_transitions_per_env} steps). "
        "Call clear() before collecting another iteration."
      )
    self.observations[self.step] = observations
    self.actions[self.step] = actions
    self.old_log_probs[self.step] = log_probs
    self.rewards[self.step] = rewards
    self.dones[self.step] = dones.float()
    self.values[self.step] = values
    self.step += 1

  def clear(self) -> None:
    self.step = 0

  def flatten(self) -> tuple[torch.Tensor, ...]:
    """Collapse [T, N, ...] -> [T*N, ...] for a single full-batch update.

    Returns (observations, actions, old_log_probs, returns, advantages).
    """
    t, n = self.num_transitions_per_env, self.num_envs
    return (
      self.observations.reshape(t * n, -1),
      self.actions.reshape(t * n, -1),
      self.old_log_probs.reshape(t * n),
      self.returns.reshape(t * n),
      self.advantages.reshape(t * n),
    )

  def minibatch_generator(
    self, num_mini_batches: int, num_epochs: int = 1
  ) -> Generator[tuple[torch.Tensor, ...], None, None]:
    """Shuffled minibatches over the flattened buffer. Unused by REINFORCE.

    Yields the same 5-tuple as `flatten()`, one minibatch at a time, for
    `num_epochs * num_mini_batches` iterations total. This is the seam PPO needs.
    """
    obs, actions, old_log_probs, returns, advantages = self.flatten()
    batch_size = obs.shape[0]
    mini_batch_size = batch_size // num_mini_batches
    for _ in range(num_epochs):
      indices = torch.randperm(batch_size, device=self.device)
      for i in range(num_mini_batches):
        idx = indices[i * mini_batch_size : (i + 1) * mini_batch_size]
        yield (
          obs[idx],
          actions[idx],
          old_log_probs[idx],
          returns[idx],
          advantages[idx],
        )
